version: '3.7'
services:
    nginx:
        image: nginx:latest
        volumes:
            - ./backend:/var/www
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - app
        ports:
            - "8282:80"
        container_name: nginx
        networks:
            - app-network
    app:
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        environment:
            - APP_URL=localhost:9000
            - DATABASE_URL=postgresql://admin:admin@db:5432/backend
        volumes:
            - ./backend:/var/www
            - ./entrypoints/entrypoint.sh:/var/tmp/entrypoint.sh:ro
            - ./log:/var/log/nginx
        depends_on:
            - db
        entrypoint: /var/tmp/entrypoint.sh
        container_name: backend
        healthcheck:
            test: curl --fail nginx || exit 1
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 2m
        expose:
            - 9000
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - app-network
    mercure:
        image: dunglas/mercure
        restart: unless-stopped
        environment:
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
        healthcheck:
            test: [ "CMD", "curl", "-f", "https://localhost/healthz" ]
            timeout: 5s
            retries: 5
            start_period: 60s
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - mercure_data:/data
            - mercure_config:/config
    db:
        image: postgres:15.3
        restart: always
        environment:
            POSTGRES_DB: backend
            POSTGRES_PASSWORD: admin
            POSTGRES_USER: admin
        expose:
            - 5432
        ports:
            - "5432:5432"
        container_name: db
        volumes:
            - dbdata:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}" ]
            timeout: 5s
            retries: 5
            start_period: 60s
        networks:
            - app-network
    front:
        build:
            context: frontend
            dockerfile: ../node.Dockerfile
        expose:
            - 3000
        ports:
            - "3000:3000"
        container_name: frontend
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
volumes:
    mercure_data:
    mercure_config:
    dbdata:
